<?php
/**
 * Uninstall script for WP Blog Agent
 * Runs when the plugin is deleted from WordPress
 */

// Exit if uninstall not called from WordPress
if (!defined('WP_UNINSTALL_PLUGIN')) {
    exit;
}

global $wpdb;

// Delete plugin options
delete_option('wp_blog_agent_ai_provider');
delete_option('wp_blog_agent_openai_api_key');
delete_option('wp_blog_agent_gemini_api_key');
delete_option('wp_blog_agent_schedule_enabled');
delete_option('wp_blog_agent_schedule_frequency');
delete_option('wp_blog_agent_auto_publish');

// Drop custom table
$table_name = $wpdb->prefix . 'blog_agent_topics';
$wpdb->query("DROP TABLE IF EXISTS $table_name");

// Delete post metadata created by the plugin
$wpdb->query("DELETE FROM {$wpdb->postmeta} WHERE meta_key LIKE '_wp_blog_agent_%'");

// Clear scheduled cron events
wp_clear_scheduled_hook('wp_blog_agent_generate_post');

// Optional: Delete all posts generated by the plugin
// Uncomment the following lines if you want to remove generated posts on uninstall
/*
$args = array(
    'post_type' => 'post',
    'posts_per_page' => -1,
    'meta_query' => array(
        array(
            'key' => '_wp_blog_agent_generated',
            'value' => true,
            'compare' => '='
        )
    )
);

$query = new WP_Query($args);
if ($query->have_posts()) {
    while ($query->have_posts()) {
        $query->the_post();
        wp_delete_post(get_the_ID(), true);
    }
}
wp_reset_postdata();
*/
