<div class="wrap">
    <h1><?php echo esc_html__('Generated Posts', 'wp-blog-agent'); ?></h1>
    
    <?php
    // Display messages
    if (isset($_GET['generated'])) {
        $post_id = intval($_GET['generated']);
        $edit_link = get_edit_post_link($post_id);
        $view_link = get_permalink($post_id);
        echo '<div class="notice notice-success is-dismissible"><p>' . 
             sprintf(
                 esc_html__('Post generated successfully! %s | %s', 'wp-blog-agent'),
                 '<a href="' . esc_url($edit_link) . '">' . esc_html__('Edit Post', 'wp-blog-agent') . '</a>',
                 '<a href="' . esc_url($view_link) . '" target="_blank">' . esc_html__('View Post', 'wp-blog-agent') . '</a>'
             ) . 
             '</p></div>';
    }
    ?>
    
    <?php
    // Get all posts generated by the plugin
    $args = array(
        'post_type' => 'post',
        'posts_per_page' => 20,
        'meta_query' => array(
            array(
                'key' => '_wp_blog_agent_generated',
                'value' => true,
                'compare' => '='
            )
        ),
        'orderby' => 'date',
        'order' => 'DESC'
    );
    
    $query = new WP_Query($args);
    
    if ($query->have_posts()) {
        ?>
        <table class="wp-list-table widefat fixed striped">
            <thead>
                <tr>
                    <th><?php echo esc_html__('Title', 'wp-blog-agent'); ?></th>
                    <th><?php echo esc_html__('Status', 'wp-blog-agent'); ?></th>
                    <th><?php echo esc_html__('Provider', 'wp-blog-agent'); ?></th>
                    <th><?php echo esc_html__('Keywords', 'wp-blog-agent'); ?></th>
                    <th><?php echo esc_html__('Date', 'wp-blog-agent'); ?></th>
                    <th><?php echo esc_html__('Actions', 'wp-blog-agent'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php while ($query->have_posts()) : $query->the_post(); ?>
                <tr>
                    <td>
                        <strong>
                            <a href="<?php echo get_edit_post_link(); ?>"><?php the_title(); ?></a>
                        </strong>
                    </td>
                    <td>
                        <?php
                        $status = get_post_status();
                        $status_labels = array(
                            'publish' => __('Published', 'wp-blog-agent'),
                            'draft' => __('Draft', 'wp-blog-agent'),
                            'pending' => __('Pending', 'wp-blog-agent'),
                            'future' => __('Scheduled', 'wp-blog-agent')
                        );
                        echo esc_html($status_labels[$status] ?? ucfirst($status));
                        ?>
                    </td>
                    <td>
                        <?php 
                        $provider = get_post_meta(get_the_ID(), '_wp_blog_agent_provider', true);
                        echo esc_html(ucfirst($provider));
                        ?>
                    </td>
                    <td>
                        <?php 
                        $keywords = get_post_meta(get_the_ID(), '_wp_blog_agent_keywords', true);
                        echo esc_html(mb_strimwidth($keywords, 0, 50, '...'));
                        ?>
                    </td>
                    <td>
                        <?php echo get_the_date(); ?>
                    </td>
                    <td>
                        <a href="<?php echo get_edit_post_link(); ?>" class="button button-small">
                            <?php echo esc_html__('Edit', 'wp-blog-agent'); ?>
                        </a>
                        <?php if (get_post_status() === 'publish') : ?>
                        <a href="<?php echo get_permalink(); ?>" class="button button-small" target="_blank">
                            <?php echo esc_html__('View', 'wp-blog-agent'); ?>
                        </a>
                        <?php endif; ?>
                        <button type="button" class="button button-small wp-blog-agent-generate-seo" data-post-id="<?php echo get_the_ID(); ?>">
                            <?php echo esc_html__('Generate SEO', 'wp-blog-agent'); ?>
                        </button>
                        <button type="button" class="button button-small wp-blog-agent-generate-image" data-post-id="<?php echo get_the_ID(); ?>">
                            <?php echo esc_html__('Generate Image', 'wp-blog-agent'); ?>
                        </button>
                    </td>
                </tr>
                <?php endwhile; ?>
            </tbody>
        </table>
        
        <?php
        // Pagination
        $total_pages = $query->max_num_pages;
        if ($total_pages > 1) {
            echo '<div class="tablenav"><div class="tablenav-pages">';
            echo paginate_links(array(
                'base' => add_query_arg('paged', '%#%'),
                'format' => '',
                'prev_text' => __('&laquo;'),
                'next_text' => __('&raquo;'),
                'total' => $total_pages,
                'current' => max(1, get_query_var('paged'))
            ));
            echo '</div></div>';
        }
        
        wp_reset_postdata();
    } else {
        echo '<p>' . esc_html__('No generated posts yet. Configure your settings and topics to start generating content.', 'wp-blog-agent') . '</p>';
        echo '<p><a href="' . admin_url('admin.php?page=wp-blog-agent') . '" class="button button-primary">' . esc_html__('Go to Settings', 'wp-blog-agent') . '</a></p>';
    }
    ?>
</div>
